name: Deploy Yelb App to ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy CloudFormation
      run: |
        aws cloudformation deploy \
          --template-file iac/base-infra-cfn.yaml \
          --stack-name yelb-stack \
          --capabilities CAPABILITY_NAMED_IAM

    - name: Get Output URL
      run: |
        aws cloudformation describe-stacks \
          --stack-name yelb-stack \
          --query "Stacks[0].Outputs"